clusterDomain: cluster.local
config:
  dbms.config.strict_validation: 'false'
env: {}
fullnameOverride: ''
image:
  imagePullPolicy: IfNotPresent
jvm:
  additionalJvmArguments: []
  useNeo4jDefaultJvmArguments: true
livenessProbe:
  failureThreshold: 40
  periodSeconds: 5
  timeoutSeconds: 10
logInitialPassword: true
nameOverride: ''
neo4j:
  acceptLicenseAgreement: 'no'
  edition: community
  labels: null
  name: neo4j01
  offlineMaintenanceModeEnabled: false
  password: Chacabuco271
  resources:
    cpu: 1000m
    memory: 2Gi
nodeSelector: null
podSpec:
  annotations: null
  containers: []
  initContainers: []
  loadbalancer: include
  nodeAffinity: null
  podAntiAffinity: true
  priorityClassName: ''
  serviceAccountName: ''
  terminationGracePeriodSeconds: 3600
  tolerations: null
readinessProbe:
  failureThreshold: 20
  periodSeconds: 5
  timeoutSeconds: 10
securityContext:
  fsGroup: 7474
  fsGroupChangePolicy: Always
  runAsGroup: 7474
  runAsNonRoot: true
  runAsUser: 7474
services:
  admin:
    annotations: {}
    enabled: true
    spec:
      type: ClusterIP
  default:
    annotations: {}
  internals:
    annotations: {}
    enabled: false
  neo4j:
    annotations: {}
    enabled: true
    ports:
      backup:
        enabled: false
      bolt:
        enabled: true
      http:
        enabled: true
      https:
        enabled: true
    spec:
      type: ClusterIP
ssl:
  bolt:
    privateKey:
      secretName: null
      subPath: null
    publicCertificate:
      secretName: null
      subPath: null
    revokedCerts:
      sources: []
    trustedCerts:
      sources: []
  https:
    privateKey:
      secretName: null
      subPath: null
    publicCertificate:
      secretName: null
      subPath: null
    revokedCerts:
      sources: []
    trustedCerts:
      sources: []
startupProbe:
  failureThreshold: 1000
  periodSeconds: 5
statefulset:
  metadata:
    annotations: null
volumes:
  backups:
    mode: share
    share:
      name: data
  data:
    mode: "volume"
    volume:
      persistentVolumeClaim:
        claimName: neo4j-pvc
  import:
    mode: share
    share:
      name: data
  licenses:
    mode: share
    share:
      name: data
  logs:
    mode: share
    share:
      name: data
  metrics:
    mode: share
    share:
      name: data
